# Footballing

We will attempt to strip historical win/loss data from a website for future ML projects.

[The historical website](https://www.pro-football-reference.com)

[Work spreadsheet for designs](https://docs.google.com/spreadsheets/d/1MkQ_J3gGDs_vkkERELOZojhwS9Wt-1eX4vFL7VP9TQE/edit#gid=0)

In [24]:
import sys
import pandas as pd

sys.path.insert(0, '..')
import lib.game_utils as gu

import lib.fetch_games as fetch_games


GAMES_DATA_PATH = '../../data/games'

In [25]:
def fetch_and_write_year(year):
  year_df = fetch_games.get_games_df_for_year(year)
  year_df.to_csv(f'{GAMES_DATA_PATH}/games_{year}.csv', index=False)

# PULL MULTIPLE YEARS

Each year will be written to a file. This does not combine all year files into __all_games__ file.

In [26]:
# fetch_and_write_year(2010)
# fetch_and_write_year(2011)
# fetch_and_write_year(2012)
# fetch_and_write_year(2013)
# fetch_and_write_year(2014)
# fetch_and_write_year(2015)
# fetch_and_write_year(2016)
# fetch_and_write_year(2017)
# fetch_and_write_year(2018)
# fetch_and_write_year(2019)
# fetch_and_write_year(2020)
fetch_and_write_year(2021)

# BUILD ALL GAMES FILE

Opens and combines all of the __year__ files we have in the data folder and writes the `all_games.csv` file.

In [28]:
import glob

# gather all file paths
file_paths = glob.glob(f"{GAMES_DATA_PATH}/games_*.csv")
file_paths.sort()
file_paths

all_games_df_list = []
for file_path in file_paths:
    year_df = pd.read_csv(file_path)
    all_games_df_list.append(year_df)

all_games_df = pd.concat(all_games_df_list, ignore_index=True)
all_games_df.to_csv(f'{GAMES_DATA_PATH}/all_games.csv', index=False)
all_games_df

,date,year,week,team,team_score,opponent,opponent_score,win,home
0,2010-09-09,2010,1,New Orleans Saints,14,Minnesota Vikings,9,1,1
1,2010-09-09,2010,1,Minnesota Vikings,9,New Orleans Saints,14,0,0
2,2010-09-12,2010,1,Chicago Bears,19,Detroit Lions,14,1,1
3,2010-09-12,2010,1,Detroit Lions,14,Chicago Bears,19,0,0
4,2010-09-12,2010,1,Buffalo Bills,10,Miami Dolphins,15,0,1
...,...,...,...,...,...,...,...,...,...
5549,2021-11-07,2021,9,Tennessee Titans,28,Los Angeles Rams,16,1,0
5550,2021-11-08,2021,9,Pittsburgh Steelers,29,Chicago Bears,27,1,1
5551,2021-11-08,2021,9,Chicago Bears,27,Pittsburgh Steelers,29,0,0
5552,2021-11-11,2021,10,Miami Dolphins,22,Baltimore Ravens,10,1,1
5553,2021-11-11,2021,10,Baltimore Ravens,10,Miami Dolphins,22,0,0